"""Extract and translate untranslated paragraphs."""

from pathlib import Path
import fitz

# The untranslated paragraphs identified
untranslated_paragraphs = {
    13: """When I started working on the book, Joe Biden was in the White House, demonstrators were no longer congregating outside Palantir's offices, the worst of the pandemic seemed over, and I did wonder if we were entering a period that would be uneventful for Karp and the company. But just weeks into my reporting, Russia invaded Ukraine, a conflict in which Palantir's technology would play a central role. Dramatic advances in machine-learning capabilities, underscored by the debut in November 2022 of ChatGPT, heralded the dawn of the AI revolution, and on both the military and commercial side, Palantir was at its vanguard. Then came October 7, the Hamas attack that left 1,200 Israelis dead. This tragedy was one of the defining events of Karp's career and an epochal moment for Palantir—it was the war on terrorism anew, in a world that now felt very unsafe for Jews, very unsafe for Alex Karp. All the major themes of Karp's life—his sense of vulnerability, his deep attachment to his Jewish heritage (in contrast to his seeming ambivalence about being part black), his disdain for the identarian left and for academia—converged around this one issue, and listening to him in the days and weeks following the massacre was especially revealing.
The slaughter in Israel also cemented his political metamorphosis. Although he had long ago stopped describing himself as a neo-socialist, he still claimed to""",
    24: """And he cared deeply about what they thought of him. At the World Economic Forum in Davos, Switzerland, in 2022, he was interviewed by CNBC's Andrew Ross Sorkin. CNBC loved having Karp as a guest; in contrast to most other CEOs, he was reliably unfiltered, thanks in part to his practice of getting hopped-up on Mexican Coke beforehand. Booking Karp almost always guaranteed headlines. I was with Karp in Davos, and as we walked to the CNBC set, he said he never got nervous before going on television but did feel a very specific kind of pressure: "I just don't ever want to say anything that would embarrass Palantirians." The interview with Sorkin was typical Karp—he was by turns funny, caustic (he teed off, as always, on Wall Street analysts), and apocalyptic about the state of the world (this was three months after Russia invaded Ukraine, and Karp suggested that there was a 20–30 percent chance that Moscow would use a nuclear weapon in the conflict). With the cameras still rolling, Sorkin had Karp teach him several tai chi moves. CNBC showed clips of the interview throughout the day. One aired while Karp and a number of Palantir employees were milling around the pavilion that the company had rented. Everyone turned to face the television except Karp: he was watching his colleagues watching him. As they laughed at his comments, he remained expressionless, just observing. It was clear that their verdict mattered a lot to him.""",
    28: """All that said, Karp was hardly a pushover boss. His jocular manner belied a driven and demanding personality. While he understood that employees had lives outside Palantir, he got frustrated if he sensed they were not putting the company first. In the wake of the pandemic, he was often irritated by how it had changed attitudes and mores—the rise of remote work, the desire for greater work-life balance. There was some irony in this (perhaps some hypocrisy, too), in that the way he chose to work and live imposed unusual burdens on the people who answered to him. Employees often had to travel to various Karp homes to see him. During the summer, a steady flow of Palantirians would head to his place in New Hampshire. Sometimes they had to go to Alaska to meet with him at his house near Anchorage. A group once went to Northern Sweden with Karp because the first cross-country trails of the season had opened and he wanted to mix business with his own recreation (they stayed in heated huts while there). "It could be said that this is a company that works around the CEO's lifestyle," one Palantir executive drolly commented.
Karp took up cross-country skiing during his first trip to the World Economic Forum, in 2016. He didn't want to go to Davos—he generally avoided conferences and crowds. As an inducement, a colleague mentioned that Davos was renowned for its cross-country skiing trails. Karp gave it a try while there and was hooked. According to Karp, as his skiing improved, members of his security detail had trouble keeping up. He also worried that they wouldn't be able to help him out if a heavy snowstorm struck while he was skiing; this was a particular risk if one went off-trail, as he sometimes did. A friend suggested that Karp try to recruit ex–Norwegian soldiers to serve as his skiing companions—they were often very accomplished skiers and were trained to operate in difficult winter weather. Karp was eventually introduced to a former member of the Norwegian special forces, a unit known as the FSK. He agreed to join Karp's security team and became his regular skiing partner. In time, Karp hired several other FSK veterans. He referred to them collectively as "the Norwegians" and also referred to them that way individually. "You should talk to the Norwegian," he would say to me, pointing to whichever handsome Nordic guy happened to be with him at that moment. The Norwegians took turns traveling with Karp;""",
    170: """Karp was also eager to talk about Palantir and Ukraine because it was a way of deflecting attention from the company's sagging stock price and Wall Street's deepening skepticism. After trading as high as $45 per share in early 2021, Palantir's stock had steadily declined, and by the time Russia invaded Ukraine, it was barely above $10. True, it had been swept up in a general sell-off of tech stocks, but it was also the case that the market just didn't see Palantir as a winning investment. A headline in the Financial Times took Karp's words and used them against the company: "Palantir: Built for Bad Times (But Maybe Not These Bad Times)." The disconnect between the importance of the work that Palantir was doing and the value that the market placed on that work was large—and, for Palantirians, not a little maddening.
For Karp, the war in Ukraine was an opportunity, as well, to rally his own troops. The company was still full of industrious, ambitious people, but two years of Covid lockdowns, as well as the controversies that had dogged Palantir,""",
    171: """Three years before Russia invaded Ukraine, Palantir started working on Project Maven, the Pentagon's artificial intelligence program, taking over for Google. According to Doug Philippone, Defense Department officials approached other tech companies first and reached out to Palantir only as a last resort because they were put off by the turmoil surrounding the firm at that time. For his part, Philippone was wary of getting involved with Maven. While the future of warfare undoubtedly revolved around AI, Maven had become a costly flop—the AI technology just wasn't good. Philippone says that the algorithms that were supposed to be able to identity, say, objects being surveilled by a drone were not up to the task: a sheep standing in a field would be mistakenly flagged as a man""",
    172: """By the time Russia invaded Ukraine, Maven had become a formidable asset, dramatically improving the military's situational awareness in combat zones and accelerating the so-called kill chain, the time between the identification of a target and its destruction or liquidation. The Biden administration sought to aid Ukraine without putting the United States in direct conflict with Russia, and Maven was integral to this strategy. Operating out of a secret site in Germany known as "The Pit," the Army's 18th Airborne Corps, under the direction of Lieutenant General Christopher Donahue (who would later oversee the evacuation of Kabul Airport), used Maven to track Russian troop movements. The system ingested and analyzed vast quantities of satellite and drone imagery to show where Russian forces were attacking or massing in preparation for an assault; where Russian munition depots were located; and other vital intelligence. The U.S. shared this information with the Ukrainians, which helped them mount unexpectedly effective resistance during the first months of the war.
But via Foundry, Maven was able to deliver much more than just an exquisitely detailed view of the battlefield. Palantir's technology also enabled Donahue's team to pull in cellular data. As it happened, many Russian soldiers—including, it turned out, commanding officers—were using their personal cell phones to communicate because their military-issued phones didn't work. This allowed the Americans to identify their precise locations, information then shared with the Ukrainians. "It was the war on terror all over again," Philippone""",
    176: """But after the trip to Kyiv, he decided to ease up on the "batshit-crazy" schtick. Perceptions of him had changed, he realized, and the faux-self-deprecatory stuff was now off-key. Putin's invasion of Ukraine had destabilized the world, and the moment demanded a different kind of public engagement on his part. His reputation was also enhanced because he projected seriousness at a time when other figures in the tech world were seen as increasingly absurd. While Karp was talking about war and peace, Mark Zuckerberg was trying to transport humanity to the metaverse, and Elon Musk was embroiled in a soap""",
}

print("需要翻译的段落已提取")
print(f"共 {len(untranslated_paragraphs)} 个段落")
for page, text in untranslated_paragraphs.items():
    print(f"\nPage {page}: {len(text)} 字符")
    print(f"前100字符: {text[:100]}...")
